export const actionType = {
  SET_LOADING: 'SET_LOADING',
  SET_ROWS: 'SET_ROWS',
  SET_PAGE_NUMBER: 'SET_PAGE_NUMBER',
  SET_PAGE_SIZE: 'SET_PAGE_SIZE',
  SET_SORT: 'SET_SORT',
  SET_FILTER: 'SET_FILTER',
  SET_TOTAL: 'SET_TOTAL'
}